{% set version = "0.1.0" %}

package:
  name: cycsm
  version: {{ version }}

source:
  git_url: https://github.com/USGS-Astrogeology/CSM-CyCSM
  git_rev: master

build:
  number: 1
  skip: True  # [not py3k]

detect_binary_files_with_prefix: true

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.10
    - cython >=0.23
    - libcsm
  run:
    - python
    - numpy >=1.10
    - libcsm

test:
  imports:
    - cycsm

about:
  home: https://github.com/USGS-Astrogeology/CSM-CyCSM
  license: Unlicense
