{% set version = "0.1.0" %}

package:
  name: cycsm
  version: {{ version }}

source:
  path: /Users/jlaura/github/usgs_csm/CSM-CyCSM 
  #git_url: https://github.com/USGS-Astrogeology/CSM-CyCSM
  #git_rev: master

build:
  number: 0

requirements:
  build:
    - python >=3.*
    - setuptools
    - numpy >=1.10
    - cython >=0.23
    - libcsm
  run:
    - python >=3.*
    - numpy >=1.10
    - libcsm

test:
  imports:
    - cycsm

about:
  home: https://github.com/USGS-Astrogeology/CSM-CyCSM
  license: Unlicense
