{% set version = "0.1.1" %}

package:
  name: cycsm
  version: {{ version }}

source:
  git_url: https://github.com/USGS-Astrogeology/CSM-CyCSM
  git_rev: master

build:
  number: 4

detect_binary_files_with_prefix: true

requirements:
  build: 
    - {{ compiler('cxx') }}
    - vc 14  # [win and py>=35]
  host:
    - python
    - setuptools
    - numpy >=1.10
    - cython >=0.27
    - libcsm
  run:
    - python
    - numpy >=1.10
    - libcsm
    - vc 14  # [win and py>=35]

test:
  imports:
    - cycsm

about:
  home: https://github.com/USGS-Astrogeology/CSM-CyCSM
  license: Unlicense
