
language: python

python:
  - "3.5"
  - "3.6"
os:
  - linux
  - osx

branches:
  only:
    - master

install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    else
        curl -o miniconda.sh  https://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh;
    fi

  # More conda setup to get miniconda in and a virtual env. setup
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a   # Useful for debugging any issues with conda

  # Install dependencies
  - conda config --add channels usgs-astrogeology
  - conda config --add channels conda-forge
  - conda install -c conda-forge numpy cython
  - conda install -c usgs-astrogeology libcsm

  # Development installation
  - conda install pytest pytest-cov
  - pip install coveralls

script:
  - python setup.py install
  - pytest --cov=cycsm
  # clean up any remaining processes...

after_success:
  - coveralls
  - conda install conda-build && conda install anaconda-client && conda config --set anaconda_upload yes &&
  conda build --token $CONDA_UPLOAD_TOKEN .
