language: generic

matrix:
  include:
    - os: linux
      env:
        - PYTHON_VERSION=3.5
    - os: linux
      env:
        - PYTHON_VERSION=3.6
    - os: osx
      osx_image: xcode9.1
      sudo: false
      compiler:
        - clang
      env:
        - PYTHON_VERSION=3.5
    - os: osx
      osx_image: xcode9.1
      sudo: false
      compiler:
        - clang
      env:
        - PYTHON_VERSION=3.6

branches:
  only:
    - master

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      curl -o miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh;
    fi

  # More conda setup to get miniconda in and a virtual env. setup
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a   # Useful for debugging any issues with conda
  # Add the necessary channels
  - conda config --add channels conda-forge
  - conda config --add channels usgs-astrogeology
  - conda install pytest pytest-cov coveralls conda-build anaconda-client

script:
  - conda build -q --token $CONDA_UPLOAD_TOKEN --python $PYTHON_VERSION .

after_success:
  - coveralls

  
