# Build worker image (VM template)
image: Visual Studio 2017

branches:
  only:
  - master

version: '0.1.0.{build}'

platform:
  - x64

configuration:
  - Release

install:
  - cmd: call C:\\Miniconda36-x64\Scripts\activate.bat
  - cmd: conda config --set always_yes yes --set changeps1 no
  - cmd: conda update -q conda
  - cmd: conda config --add channels usgs-astrogeology
  - cmd: conda config --add channels conda-forge
  - cmd: conda install -c conda-forge numpy cython pytest
  - cmd: conda install -c usgs-astrogeology libcsm
  - cmd: conda install conda-build anaconda-client
  - cmd: conda config --set anaconda_upload yes
  - conda build --token %CONDA_UPLOAD_TOKEN% .

build_script:
  # Have to setup the VS17 env. first
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - python setup.py install

test_script:
  - pytest --cov=cycsm

on_success:
  - cmd: conda build --token %CONDA_UPLOAD_TOKEN% .
